### PR TITLE
Revise docs

### PR DESCRIPTION
**Pull request by temptemp3**
* Added semi-colon to match whole program version

### CODE REVIEW

**Comment by jeapostrophe** [comment]
This is good; however, you should clean up your branch so that the previous commits don't show up on the pull request display. I think this will happen automatically by rebasing your branch.

**Comment by temptemp3** [comment]
Sounds good. So far all of the editing I have done has been using GitHub. I'll experiment with a workflow that doesn't result in previous commits showing up in the pull request display. Thanks

**Comment by temptemp3** [comment]
About pull request merges
https://docs.github.com/en/github/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges

**Comment by temptemp3** [comment]
Git rebase from remote fork repo 
https://gist.github.com/ravibhure/a7e0918ff4937c9ea1c456698dcd58aa

**Comment by temptemp3** [comment]
Okay. I just noticed that there are now more commits.

**Comment by jeapostrophe** [comment]
You want to make it so that this page --- https://github.com/reach-sh/reach-lang/pull/180/commits --- only has one commit listed. You do this by rebasing your repo. Another way is not modify `master` on your repo, but by using a branch and then sending a pr for that branch

**Comment by temptemp3** [comment]
👍

**Comment by temptemp3** [comment]
Ended up creating a new PR
https://github.com/reach-sh/reach-lang/pull/181
Anyways, thanks for the help. I appreciate it.

**Pull request closed without merging**
