### PR TITLE
WIP - working on BytesDyn casting

### PR DESCRIPTION
**Pull request by willghatch**
I wanted to push this branch to get some comments.

(1) I think I can't call the casting function `BytesDyn` because in the default environment `BytesDyn` returns a type, not an `SLPrim`.  I could probably call it `BytesDyn.cast()` by adding the the type to `evalAsEnvM`.  I guess that's probably what I'll ultimately do, as there is precident with eg. `Token` type being there, although I decided for now to work on it as `BytesDynCast`.  Do I understand everything correctly here?

(2) I currently have an implementation of interpreting this primitive that I think should make sense, but when I use it on the ERC721 contract (replacing the `EmptyBytesDyn` variable with `BytesDynCast("")`) and compile it I get an error because it generates (in Solidity) two copies of the `ERC721TokenReceiver` interface, one with `bytes memory` and one with `bytes0`.  It seems like something is seeing through the layer where I'm setting the type as `BytesDyn` to see the type `Bytes(0)` instead.  My plan for implementation was to use `ctxt_lift_expr` with `DLE_Arg` to just make a new DLVar that references the old one but has the new type.  But it looks like that's probably not the right approach.  Do you have a recommendation?

### CODE REVIEW

**Comment by jeapostrophe** [comment]
1. We already support calling types as functions: https://github.com/reach-sh/reach-lang/blob/master/hs/src/Reach/Eval/Core.hs#L4420-L4421

2. I don't see an example program and so it is hard for me to track things. You're going to get into trouble because you haven't changed `dlvToDL` (https://github.com/reach-sh/reach-lang/blob/master/hs/src/Reach/Eval/Core.hs#L693)

**Comment by willghatch** [comment]
I haven't rearranged things to address (1) yet, but I've now addressed (2) and I'm stuck with the same issue.  But I have a little more context for it now.  I see now that the generated solidity for ERC721 even before the change included two Solidity interface definitions for a single Reach interface definition, specifically for `onERC721Received`.  I guess this is happening due to inlining/linearization, but it surprises me that it doesn't get a cached single definition.  Anyway, with the change (that I pushed this time) of the ERC721 contract to write an empty BytesDyn instead of using one passed in, one of those solidity definitions changes from using `bytes` as its type to `bytes0`.  I can see the code in `ETH_Solidity` for `DLE_Remote` is using the arguments to generate the type (rather than using the interface definition), so it makes sense why it's generating `bytes0` if that's the type it sees there.  But... how is it passing the type check that the argument is a `BytesDyn` but then showing up as `Bytes[0]` at the level of solidity generation?  I haven't figured that out yet.  So my implementation so far seems to be able to give that expression the type `BytesDyn` in some but not all places...

**Review by jeapostrophe — COMMENTED** [review]
If you look at the intermediate files, you'll be able to see type annotations on all of the variables at every step

**Comment by willghatch** [comment]
So you said you only cared about the static case, but by then I had figured out how to do the dynamic case, and I had assumed a dynamic case initially and had already done much of the work for it.  So I ultimately implemented it for both cases, although I got stuck for a while on the SMT part for the dynamic case, which I hadn't thought about previously...

**Review by jeapostrophe — CHANGES_REQUESTED** [review]
All that is left is the changelog. Good work.

**Comment by willghatch** [comment]
Ah, sorry, I always forget about the changelog.

**Review by jeapostrophe — APPROVED** [review]

**Pull request merged**
