### PR TITLE
DCT-339

### PR DESCRIPTION
**Pull request by Craig-Elre**
Provide an example of error code, and a fix for RE0132

### CODE REVIEW

**Review by jeapostrophe — APPROVED** [review]
Does it look good?

**Comment by jeapostrophe** [comment]
Merge if so

**Comment by Craig-Elre** [comment]
> 

I am not sure which "it" you are referring to. Are you asking if the code sample is properly formed? Or does the code display correctly? Maybe something else?

**Comment by jeapostrophe** [comment]
I just mean that you looked at the site and it looks great :)

**Comment by Craig-Elre** [comment]
> I just mean that you looked at the site and it looks great :)

OK, yes it does. :-)

**Pull request merged**
